using System.Collections.Generic;
using System.Linq;
using TMPro;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.Events;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.UI;
using UnityEngine.SceneManagement;
using UnityEngine.UI;
using Draftmaster.Data;
using Draftmaster.Fans;
using Draftmaster.Sponsors;
// GarageUI declares a `Series` of its own in the global namespace, which would shadow the database model.
using SeriesInfo = Draftmaster.Data.Series;

// The garage screen, built to the Iron Oval design file's GARAGE pass: car slot and driver identity down
// the left with career and accolades under it, the driver's own stats in the middle over an XP meter, and
// the car's numbers plus fitted parts on the right.
//
// The sheet is a JRPG character sheet, so the job here is binding each field to something the game really
// keeps rather than inventing an RPG:
//
//   DRIVER INFO   the player's row in the Drivers table, found the way the rest of the game finds it —
//                 by the number on the car (PlayerDriver). Name, number, team, manufacturer, age and
//                 nickname come straight off that row.
//   DRIVER STATS  every attribute that row carries: both 0-100 ability ratings and all sixteen 0-20
//                 skills, laid out by DriverAttributeSheet. No row at all = the block reads as unrated
//                 rather than showing zeros.
//   XP            fan appeal 0-100, the progress meter this game actually has.
//   CAREER        PlayerStatsLedger counters (starts / wins / top 10s).
//   ACCOLADES     derived from those same counters, so a line only appears once it's been earned.
//   CAR STATS     the base VehicleInfo with the installed parts applied — top speed, 0-60, grip and
//                 durability are the numbers the car will actually race with.
//   FITTED PARTS  the four real part slots. Empty reads "stock", dimmed.
//
// The top bar carries two dropdowns — the series, and the field entered in it — so the sheet can be read
// for anyone on the grid, not just the player. Where a block is only true of the player (their career
// counters, their accolades, their fan appeal, the parts bolted to their car) it says so plainly rather
// than showing the player's numbers under a rival's name: SeriesRoster answers who races where, and
// nothing on this screen writes anything back.
//
// The sheet's bottom strip is a team-roster switcher; this game has one car, so that strip carries the
// weekend and the way out to the track instead.
//
// How the player gets here: the laptop in the RV or the one in the team factory, not a row on the title
// menu — see GarageScreenLoader, which also remembers which of those to send BACK to.
//
// Layout is generated by Draftmaster > Art > Build Garage Screen Scene; this only fills it in.
public class GarageScreenUI : MonoBehaviour
{
    [Header("Wired by the builder")]
    [Tooltip("Top-bar series picker. Changing it refills the driver picker with that series' entry list.")]
    public TMP_Dropdown seriesDropdown;
    [Tooltip("Top-bar driver picker: the selected series' field, by car number. Changing it redraws the sheet.")]
    public TMP_Dropdown driverDropdown;
    public TextMeshProUGUI cashLabel;
    public TextMeshProUGUI carSlotCaption;
    public TextMeshProUGUI driverName;
    public TextMeshProUGUI driverNumber;
    public TextMeshProUGUI driverLevel;
    [Tooltip("The team on the player's Drivers row, shortened to fit the column.")]
    public TextMeshProUGUI driverTeam;
    [Tooltip("Age, manufacturer and nickname off the same row, on one line.")]
    public TextMeshProUGUI driverBio;
    public TextMeshProUGUI statusLabel;
    public TextMeshProUGUI weekendLabel;

    [Tooltip("One row per DriverAttributeSheet.All entry, in that order: label, cells, value.")]
    public List<StatRow> driverStats = new();
    [Tooltip("Four car-stat rows: label, cells, value.")]
    public List<StatRow> carStats = new();
    [Tooltip("Three career rows: label, value.")]
    public List<TextPair> careerRows = new();
    [Tooltip("Accolade lines, filled top-down.")]
    public List<TextMeshProUGUI> accoladeLines = new();
    [Tooltip("Four fitted-part rows: slot, item.")]
    public List<TextPair> partRows = new();

    public RectTransform xpBar;
    public TextMeshProUGUI xpLabel;

    [Header("Flow")]
    public string raceSceneName = "RaceScene";
    [Tooltip("Where BACK goes when the sheet was opened cold rather than from a laptop in the RV or the factory.")]
    public string titleSceneName = GarageScreenLoader.TitleSceneName;

    [System.Serializable]
    public class StatRow
    {
        public TextMeshProUGUI label;
        public RectTransform cells;
        public TextMeshProUGUI value;
        [Tooltip("Cell colour. Gold for the driver's stats, telemetry blue for the car's, as the sheet has it.")]
        public Color tint = new Color(0.91f, 0.69f, 0.24f, 1f);
    }

    [System.Serializable]
    public class TextPair
    {
        public TextMeshProUGUI label;
        public TextMeshProUGUI value;
    }

    float _statusUntil;

    // What the top bar is currently pointed at.
    List<SeriesInfo> _series = new();
    List<Driver> _field = new();
    Driver _viewed;
    // False until the pickers have been filled — a sheet built before they existed still shows the
    // player rather than an empty column.
    bool _browsing;
    // Set while options are being rebuilt, so SetValue's own callback can't re-enter and rebuild again.
    bool _populating;

    void Start()
    {
        IronOvalScanlines.Ensure();
        if (EventSystem.current == null)
            new GameObject("EventSystem", typeof(EventSystem), typeof(InputSystemUIInputModule));
        WireButtons();
        BuildPickers();
        Refresh();
    }

    // RACE and BACK, hooked up here for the same reason the pickers are: the builder that generates this
    // scene calls onClick.AddListener at edit time, which adds a RUNTIME listener and is thrown away when
    // the scene is saved. The buttons in the saved scene therefore have an empty onClick, and the only
    // wiring that survives is the wiring done in code, on the way up.
    //
    // Found by the names the builder gives them rather than by serialized references, so a rebuilt scene
    // needs no re-dragging. RACE sits on its own object; BACK is a tab, whose Button is on the face inside
    // the plate — GetComponentInChildren covers both shapes.
    void WireButtons()
    {
        Wire("Race", Race);
        Wire("Back", Back);
    }

    void Wire(string objectName, UnityAction action)
    {
        var owner = FindDescendant(transform, objectName);
        if (owner == null)
        {
            Debug.LogWarning($"GarageScreenUI: no '{objectName}' button in the scene — rebuild it with " +
                             "Draftmaster > Art > Build Garage Screen Scene.");
            return;
        }

        var button = owner.GetComponentInChildren<Button>(true);
        if (button == null)
        {
            Debug.LogWarning($"GarageScreenUI: '{objectName}' has no Button, so it can't be pressed.");
            return;
        }

        button.onClick.RemoveListener(action);   // a rebuild in the same session must not double it up
        button.onClick.AddListener(action);
    }

    static Transform FindDescendant(Transform root, string objectName)
    {
        if (root.name == objectName) return root;
        foreach (Transform child in root)
        {
            var found = FindDescendant(child, objectName);
            if (found != null) return found;
        }
        return null;
    }

    // ------------------------------------------------------------------ top bar

    // Fill both dropdowns and open the sheet on the player: their series, their car. Listeners are added
    // here rather than baked into the scene — a UnityEvent wired at build time isn't serialised, so the
    // only wiring that survives a scene save is the wiring done in code.
    public void BuildPickers()
    {
        _series = SeriesRoster.AllSeries();
        int seriesIndex = SeriesRoster.SeriesIndexFor(_series, PlayerDriver.CarNumber);

        if (seriesDropdown != null)
        {
            _populating = true;
            seriesDropdown.ClearOptions();
            seriesDropdown.AddOptions(_series.Select(s => SeriesRoster.Label(s)).ToList());
            seriesDropdown.SetValueWithoutNotify(Mathf.Max(0, seriesIndex));
            seriesDropdown.RefreshShownValue();
            seriesDropdown.onValueChanged.RemoveListener(OnSeriesPicked);
            seriesDropdown.onValueChanged.AddListener(OnSeriesPicked);
            _populating = false;
            _browsing = true;
        }

        if (driverDropdown != null)
        {
            driverDropdown.onValueChanged.RemoveListener(OnDriverPicked);
            driverDropdown.onValueChanged.AddListener(OnDriverPicked);
            _browsing = true;
        }

        ShowField(seriesIndex, PlayerDriver.CarNumber);
    }

    // The entry list for one series, with the sheet landing on `preferredCarNumber` when that car is in
    // it. A series nobody has been entered into yet says so instead of borrowing another series' field.
    void ShowField(int seriesIndex, int preferredCarNumber)
    {
        var series = seriesIndex >= 0 && seriesIndex < _series.Count ? _series[seriesIndex] : null;
        _field = SeriesRoster.Drivers(series);
        int driverIndex = SeriesRoster.DriverIndexFor(_field, preferredCarNumber);
        _viewed = driverIndex >= 0 && driverIndex < _field.Count ? _field[driverIndex] : null;

        if (driverDropdown == null) return;

        _populating = true;
        driverDropdown.ClearOptions();
        driverDropdown.AddOptions(_field.Count > 0
            ? _field.Select(d => SeriesRoster.Label(d)).ToList()
            : new List<string> { "NO ENTRY LIST YET" });
        driverDropdown.SetValueWithoutNotify(Mathf.Max(0, driverIndex));
        driverDropdown.RefreshShownValue();
        driverDropdown.interactable = _field.Count > 1;
        _populating = false;
    }

    public void OnSeriesPicked(int index)
    {
        if (_populating) return;
        ShowField(index, PlayerDriver.CarNumber);
        Refresh();
    }

    public void OnDriverPicked(int index)
    {
        if (_populating) return;
        _viewed = index >= 0 && index < _field.Count ? _field[index] : null;
        Refresh();
    }

    // The driver the sheet is drawing. Before the pickers are filled — and on a copy of the screen built
    // before they existed — that is the player, exactly as it was.
    Driver ViewedRow() => _browsing ? _viewed : PlayerDriver.Row();

    // Whether the sheet is showing the player's own ride, which is what decides if the player-only blocks
    // (career, accolades, fan appeal, the car and its parts) are theirs to fill.
    bool ViewingPlayer(Driver row)
    {
        if (!_browsing) return true;
        int mine = PlayerDriver.CarNumber;
        return row != null && mine > 0 && row.CarNumber == mine;
    }

    void Update()
    {
        var kb = Keyboard.current;
        if (kb != null && (kb.escapeKey.wasPressedThisFrame || kb.backspaceKey.wasPressedThisFrame)) Back();
        if (_statusUntil > 0f && Time.unscaledTime >= _statusUntil) SetStatus("");
    }

    // ------------------------------------------------------------------ content

    public void Refresh()
    {
        var theme = PixelUITheme.Instance;

        // One lookup for the whole sheet: the driver the top bar is pointed at, which starts out as the
        // Drivers row behind the number the player races.
        var row = ViewedRow();
        bool mine = ViewingPlayer(row);

        int number = row != null ? row.CarNumber : (mine ? PlayerDriver.CarNumber : 0);
        if (cashLabel != null) cashLabel.text = PlayerWallet.CashText;
        if (carSlotCaption != null)
            carSlotCaption.text = number > 0 ? $"[ car sprite — #{number} ]" : "[ no car ]";
        // Only the player's own name is overridden by their career name; a rival keeps theirs.
        if (driverName != null)
            driverName.text = (mine ? PlayerDriver.DisplayName(row) : FullName(row)).ToUpperInvariant();
        if (driverNumber != null) driverNumber.text = number > 0 ? "#" + number : "#—";
        FillIdentity(theme, row);

        int starts = PlayerStatsLedger.Get("starts");
        int wins = PlayerStatsLedger.Get("wins");
        int top10s = PlayerStatsLedger.Get("top10s");
        int top5s = PlayerStatsLedger.Get("top5s");

        // The sheet's LV. Seasons aren't levelled, so this reads the one ladder that exists: races run —
        // and only the player has run any, so a rival's level is blank rather than borrowed.
        if (driverLevel != null)
        {
            driverLevel.text = mine ? "LV " + (1 + starts / 5) : "LV —";
            if (theme != null) driverLevel.color = mine ? theme.textDim : theme.textDisabled;
        }

        FillCareer(mine, starts, wins, top10s);
        FillAccolades(theme, mine, starts, wins, top5s, top10s);
        FillDriverStats(theme, row);
        FillCarStats(mine);
        FillParts(theme, mine);

        // The player's fan appeal is the meter this game keeps; a rival's standing with the crowd is the
        // Fan Support their row is rated on, put on the same 0-100 scale.
        float appeal = mine ? FanAppeal.Value
                            : (row != null ? row.FanSupport * 100f / Driver.StatMax : 0f);
        SetBar(xpBar, appeal / 100f);
        if (xpLabel != null) xpLabel.text = Mathf.RoundToInt(appeal) + "/100";

        if (weekendLabel != null)
        {
            string track = TrackSelection.CurrentDisplayName;
            string session = RaceWeekend.IsQualifying ? "QUALIFYING" : RaceWeekend.IsPractice ? "PRACTICE" : "RACE";
            weekendLabel.text = string.IsNullOrEmpty(track)
                ? "NO TRACK SELECTED"
                : $"NEXT: {track.ToUpperInvariant()} · {session}";
        }
    }

    // The ledger counts the player's races and nobody else's, so a rival's career reads as unrecorded
    // rather than being handed the player's numbers.
    void FillCareer(bool mine, int starts, int wins, int top10s)
    {
        SetPair(careerRows, 0, "STARTS", mine ? starts.ToString() : "—");
        SetPair(careerRows, 1, "WINS", mine ? wins.ToString() : "—");
        SetPair(careerRows, 2, "TOP 10s", mine ? top10s.ToString() : "—");
    }

    // Every line here is something the ledger can prove. Nothing earned yet says so plainly.
    void FillAccolades(PixelUITheme theme, bool mine, int starts, int wins, int top5s, int top10s)
    {
        var lines = new List<(string text, bool gold)>();
        if (!mine)
        {
            // Nothing in the ledger is about this driver, and the database keeps no honours roll yet.
            lines.Add(("NO CAREER RECORD ON FILE", false));
        }
        else
        {
            if (wins > 0) lines.Add(($"{wins} RACE WIN{(wins == 1 ? "" : "S")}", true));
            if (top5s > 0) lines.Add(($"{top5s} TOP FIVE{(top5s == 1 ? "" : "S")}", true));
            if (PlayerStatsLedger.Get("fights.won") > 0)
                lines.Add(($"{PlayerStatsLedger.Get("fights.won")}× WON A PADDOCK SCRAP", false));
            if (PlayerStatsLedger.Get("locations") > 0)
                lines.Add(($"{PlayerStatsLedger.Get("locations")} PLACES VISITED", false));
            if (lines.Count == 0)
                lines.Add((starts > 0 ? "NOTHING TO PUT ON THE WALL YET" : "NO STARTS YET", false));
        }

        for (int i = 0; i < accoladeLines.Count; i++)
        {
            var label = accoladeLines[i];
            if (label == null) continue;
            if (i < lines.Count)
            {
                label.text = lines[i].text;
                if (theme != null) label.color = lines[i].gold ? theme.gold : theme.textDim;
                label.gameObject.SetActive(true);
            }
            else label.gameObject.SetActive(false);
        }
    }

    // The rest of the driver's database row: who they drive for, what they drive and how old they are.
    void FillIdentity(PixelUITheme theme, Driver row)
    {
        if (driverTeam != null)
        {
            string team = row != null ? PlayerDriver.ShortTeamName(row.TeamName) : "";
            driverTeam.text = team.Length > 0 ? team.ToUpperInvariant() : "NO TEAM";
            if (theme != null) driverTeam.color = team.Length > 0 ? theme.text : theme.textDisabled;
        }

        if (driverBio == null) return;

        if (row == null)
        {
            driverBio.text = "NO DRIVER RECORD";
            if (theme != null) driverBio.color = theme.textDisabled;
            return;
        }

        var parts = new List<string>(3);
        if (row.Age > 0) parts.Add("AGE " + row.Age);
        if (!string.IsNullOrWhiteSpace(row.Manufacturer)) parts.Add(row.Manufacturer.Trim().ToUpperInvariant());
        if (!string.IsNullOrWhiteSpace(row.Nickname)) parts.Add("\"" + row.Nickname.Trim().ToUpperInvariant() + "\"");

        driverBio.text = string.Join(" · ", parts);
        if (theme != null) driverBio.color = theme.textDim;
    }

    // Every attribute the Drivers table rates this driver on, in DriverAttributeSheet order — the same
    // order the builder laid the rows out in. A save with no row at all reads as unrated rather than
    // drawing eighteen empty bars.
    void FillDriverStats(PixelUITheme theme, Driver row)
    {
        var sheet = DriverAttributeSheet.All;
        for (int i = 0; i < driverStats.Count && i < sheet.Length; i++)
        {
            var attribute = sheet[i];
            int value = row != null ? attribute.Read(row) : -1;
            SetStat(driverStats, i, attribute.Label,
                    value >= 0 ? value / (float)Mathf.Max(1, attribute.Max) : 0f,
                    value >= 0 ? value.ToString() : "—");
            if (theme != null && driverStats[i].value != null)
                driverStats[i].value.color = value >= 0 ? theme.text : theme.textDisabled;
        }
    }

    // What the car will actually race with: the base VehicleInfo plus every installed part. Parts are the
    // player's own upgrades, so a rival's entry is the spec car — the same chassis with nothing on it.
    void FillCarStats(bool mine)
    {
        var baseInfo = Resources.Load<VehicleInfo>("Vehicles/Cup24");
        float topAdd = 0f, accelScale = 1f, gripAdd = 0f, wearScale = 1f;
        foreach (PartSlot slot in System.Enum.GetValues(typeof(PartSlot)))
        {
            var part = mine ? PlayerCarBuild.Installed(slot) : null;
            if (part == null) continue;
            topAdd += part.topSpeedAdd;
            accelScale *= part.accelScale;
            gripAdd += part.gripAdd;
            wearScale *= part.wearScale;
        }

        float topSpeed = (baseInfo != null ? baseInfo.topSpeed : 200) + topAdd;
        float zeroSixty = (baseInfo != null ? baseInfo.zeroToSixty : 3.4f) / Mathf.Max(0.1f, accelScale);
        float grip = (baseInfo != null ? baseInfo.maxLateralG : 1.5f) + gripAdd;
        float durability = 1f / Mathf.Max(0.1f, wearScale);   // >1 = tyres last longer than stock

        SetStat(carStats, 0, "TOP SPEED", Mathf.InverseLerp(150f, 230f, topSpeed), Mathf.RoundToInt(topSpeed) + " MPH");
        SetStat(carStats, 1, "ACCEL", Mathf.InverseLerp(5f, 3f, zeroSixty), "0-60 " + zeroSixty.ToString("0.0") + "s");
        SetStat(carStats, 2, "GRIP", Mathf.InverseLerp(1f, 2f, grip), grip.ToString("0.00") + " G");
        SetStat(carStats, 3, "DURABILITY", Mathf.InverseLerp(0.7f, 1.4f, durability), DurabilityWord(durability));
    }

    static string DurabilityWord(float durability) =>
        durability >= 1.25f ? "IRON" : durability >= 1.05f ? "GOOD" :
        durability >= 0.95f ? "STOCK" : durability >= 0.8f ? "FAIR" : "FRAGILE";

    void FillParts(PixelUITheme theme, bool mine)
    {
        var slots = new[] { PartSlot.Engine, PartSlot.Gearbox, PartSlot.Tires, PartSlot.Chassis };
        for (int i = 0; i < partRows.Count && i < slots.Length; i++)
        {
            var part = mine ? PlayerCarBuild.Installed(slots[i]) : null;
            SetPair(partRows, i, slots[i].ToString().ToUpperInvariant(), part != null ? part.name : "stock");
            if (theme != null && partRows[i].value != null)
                partRows[i].value.color = part != null ? theme.text : theme.textDisabled;
        }
    }

    // ------------------------------------------------------------------ helpers

    // A driver's name as their own row has it, with the timing-tower short name as the fallback. Used for
    // everyone except the player, whose career name is allowed to sit over the seat they took.
    static string FullName(Driver row)
    {
        if (row == null) return "no driver";
        string full = ((row.FirstName ?? "") + " " + (row.LastName ?? "")).Trim();
        if (full.Length > 0) return full;
        string label = RosterLookup.LabelName(row);
        return label.Length > 0 ? label : "no driver";
    }

    void SetStat(List<StatRow> rows, int index, string label, float fill01, string value)
    {
        if (index < 0 || index >= rows.Count) return;
        var row = rows[index];
        if (row.label != null) row.label.text = label;
        if (row.value != null) row.value.text = value;
        if (row.cells != null)
            IronOvalUI.SetCells(row.cells, Mathf.RoundToInt(Mathf.Clamp01(fill01) * 10f), 10, row.tint);
    }

    static void SetPair(List<TextPair> rows, int index, string label, string value)
    {
        if (index < 0 || index >= rows.Count) return;
        if (rows[index].label != null) rows[index].label.text = label;
        if (rows[index].value != null) rows[index].value.text = value;
    }

    static void SetBar(RectTransform fill, float amount01)
    {
        if (fill == null || fill.parent is not RectTransform track) return;
        fill.sizeDelta = new Vector2(Mathf.Round(track.rect.width * Mathf.Clamp01(amount01)), fill.sizeDelta.y);
    }

    // ------------------------------------------------------------------ buttons (wired by the builder)

    public void Race()
    {
        if (!Application.CanStreamedLevelBeLoaded(raceSceneName))
        {
            SetStatus(raceSceneName + " isn't in the build settings yet.");
            return;
        }
        GarageScreenLoader.Clear();   // heading to the track ends the trip — BACK shouldn't return here later
        SceneManager.LoadScene(raceSceneName);
    }

    // Back to wherever the sheet was opened from — the RV or the factory when a laptop opened it, the
    // title when it was opened cold. GarageScreenLoader owns that memory; titleSceneName is the fallback
    // it falls through to, so the field still says where "nowhere to go back to" leads.
    public void Back()
    {
        if (!GarageScreenLoader.Leave(titleSceneName))
            SetStatus(titleSceneName + " isn't in the build settings yet.");
    }

    void SetStatus(string text)
    {
        if (statusLabel == null) return;
        statusLabel.text = text ?? "";
        _statusUntil = string.IsNullOrEmpty(text) ? 0f : Time.unscaledTime + 2.5f;
    }
}
