using System.Collections.Generic;
using TMPro;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.UI;
using UnityEngine.SceneManagement;
using UnityEngine.UI;
using Draftmaster.Data;
using Draftmaster.Fans;
using Draftmaster.Sponsors;

// The garage screen, built to the Iron Oval design file's GARAGE pass: car slot and driver identity down
// the left with career and accolades under it, the driver's own stats in the middle over an XP meter, and
// the car's numbers plus fitted parts on the right.
//
// The sheet is a JRPG character sheet, so the job here is binding each field to something the game really
// keeps rather than inventing an RPG:
//
//   DRIVER INFO   the player's row in the Drivers table, found the way the rest of the game finds it —
//                 by the number on the car (PlayerDriver). Name, number, team, manufacturer, age and
//                 nickname come straight off that row.
//   DRIVER STATS  every attribute that row carries: both 0-100 ability ratings and all sixteen 0-20
//                 skills, laid out by DriverAttributeSheet. No row at all = the block reads as unrated
//                 rather than showing zeros.
//   XP            fan appeal 0-100, the progress meter this game actually has.
//   CAREER        PlayerStatsLedger counters (starts / wins / top 10s).
//   ACCOLADES     derived from those same counters, so a line only appears once it's been earned.
//   CAR STATS     the base VehicleInfo with the installed parts applied — top speed, 0-60, grip and
//                 durability are the numbers the car will actually race with.
//   FITTED PARTS  the four real part slots. Empty reads "stock", dimmed.
//
// The sheet's bottom strip is a team-roster switcher; this game has one car, so that strip carries the
// weekend and the way out to the track instead.
//
// Layout is generated by Draftmaster > Art > Build Garage Screen Scene; this only fills it in.
public class GarageScreenUI : MonoBehaviour
{
    [Header("Wired by the builder")]
    public TextMeshProUGUI cashLabel;
    public TextMeshProUGUI carSlotCaption;
    public TextMeshProUGUI driverName;
    public TextMeshProUGUI driverNumber;
    public TextMeshProUGUI driverLevel;
    [Tooltip("The team on the player's Drivers row, shortened to fit the column.")]
    public TextMeshProUGUI driverTeam;
    [Tooltip("Age, manufacturer and nickname off the same row, on one line.")]
    public TextMeshProUGUI driverBio;
    public TextMeshProUGUI statusLabel;
    public TextMeshProUGUI weekendLabel;

    [Tooltip("One row per DriverAttributeSheet.All entry, in that order: label, cells, value.")]
    public List<StatRow> driverStats = new();
    [Tooltip("Four car-stat rows: label, cells, value.")]
    public List<StatRow> carStats = new();
    [Tooltip("Three career rows: label, value.")]
    public List<TextPair> careerRows = new();
    [Tooltip("Accolade lines, filled top-down.")]
    public List<TextMeshProUGUI> accoladeLines = new();
    [Tooltip("Four fitted-part rows: slot, item.")]
    public List<TextPair> partRows = new();

    public RectTransform xpBar;
    public TextMeshProUGUI xpLabel;

    [Header("Flow")]
    public string raceSceneName = "RaceScene";
    public string titleSceneName = "TitleScreen";

    [System.Serializable]
    public class StatRow
    {
        public TextMeshProUGUI label;
        public RectTransform cells;
        public TextMeshProUGUI value;
        [Tooltip("Cell colour. Gold for the driver's stats, telemetry blue for the car's, as the sheet has it.")]
        public Color tint = new Color(0.91f, 0.69f, 0.24f, 1f);
    }

    [System.Serializable]
    public class TextPair
    {
        public TextMeshProUGUI label;
        public TextMeshProUGUI value;
    }

    float _statusUntil;

    void Start()
    {
        IronOvalScanlines.Ensure();
        if (EventSystem.current == null)
            new GameObject("EventSystem", typeof(EventSystem), typeof(InputSystemUIInputModule));
        Refresh();
    }

    void Update()
    {
        var kb = Keyboard.current;
        if (kb != null && (kb.escapeKey.wasPressedThisFrame || kb.backspaceKey.wasPressedThisFrame)) Back();
        if (_statusUntil > 0f && Time.unscaledTime >= _statusUntil) SetStatus("");
    }

    // ------------------------------------------------------------------ content

    public void Refresh()
    {
        var theme = PixelUITheme.Instance;

        // One lookup for the whole sheet: the Drivers row behind the number the player races.
        var row = PlayerDriver.Row();

        int number = row != null && row.CarNumber > 0 ? row.CarNumber : PlayerDriver.CarNumber;
        if (cashLabel != null) cashLabel.text = PlayerWallet.CashText;
        if (carSlotCaption != null) carSlotCaption.text = $"[ car sprite — #{number} ]";
        if (driverName != null) driverName.text = PlayerDriver.DisplayName(row).ToUpperInvariant();
        if (driverNumber != null) driverNumber.text = "#" + number;
        FillIdentity(theme, row);

        int starts = PlayerStatsLedger.Get("starts");
        int wins = PlayerStatsLedger.Get("wins");
        int top10s = PlayerStatsLedger.Get("top10s");
        int top5s = PlayerStatsLedger.Get("top5s");

        // The sheet's LV. Seasons aren't levelled, so this reads the one ladder that exists: races run.
        if (driverLevel != null) driverLevel.text = "LV " + (1 + starts / 5);

        FillCareer(starts, wins, top10s);
        FillAccolades(theme, starts, wins, top5s, top10s);
        FillDriverStats(theme, row);
        FillCarStats();
        FillParts(theme);

        float appeal = FanAppeal.Value;
        SetBar(xpBar, appeal / 100f);
        if (xpLabel != null) xpLabel.text = Mathf.RoundToInt(appeal) + "/100";

        if (weekendLabel != null)
        {
            string track = TrackSelection.CurrentDisplayName;
            string session = RaceWeekend.IsQualifying ? "QUALIFYING" : RaceWeekend.IsPractice ? "PRACTICE" : "RACE";
            weekendLabel.text = string.IsNullOrEmpty(track)
                ? "NO TRACK SELECTED"
                : $"NEXT: {track.ToUpperInvariant()} · {session}";
        }
    }

    void FillCareer(int starts, int wins, int top10s)
    {
        SetPair(careerRows, 0, "STARTS", starts.ToString());
        SetPair(careerRows, 1, "WINS", wins.ToString());
        SetPair(careerRows, 2, "TOP 10s", top10s.ToString());
    }

    // Every line here is something the ledger can prove. Nothing earned yet says so plainly.
    void FillAccolades(PixelUITheme theme, int starts, int wins, int top5s, int top10s)
    {
        var lines = new List<(string text, bool gold)>();
        if (wins > 0) lines.Add(($"{wins} RACE WIN{(wins == 1 ? "" : "S")}", true));
        if (top5s > 0) lines.Add(($"{top5s} TOP FIVE{(top5s == 1 ? "" : "S")}", true));
        if (PlayerStatsLedger.Get("fights.won") > 0)
            lines.Add(($"{PlayerStatsLedger.Get("fights.won")}× WON A PADDOCK SCRAP", false));
        if (PlayerStatsLedger.Get("locations") > 0)
            lines.Add(($"{PlayerStatsLedger.Get("locations")} PLACES VISITED", false));
        if (lines.Count == 0)
            lines.Add((starts > 0 ? "NOTHING TO PUT ON THE WALL YET" : "NO STARTS YET", false));

        for (int i = 0; i < accoladeLines.Count; i++)
        {
            var label = accoladeLines[i];
            if (label == null) continue;
            if (i < lines.Count)
            {
                label.text = lines[i].text;
                if (theme != null) label.color = lines[i].gold ? theme.gold : theme.textDim;
                label.gameObject.SetActive(true);
            }
            else label.gameObject.SetActive(false);
        }
    }

    // The rest of the driver's database row: who they drive for, what they drive and how old they are.
    void FillIdentity(PixelUITheme theme, Driver row)
    {
        if (driverTeam != null)
        {
            string team = row != null ? PlayerDriver.ShortTeamName(row.TeamName) : "";
            driverTeam.text = team.Length > 0 ? team.ToUpperInvariant() : "NO TEAM";
            if (theme != null) driverTeam.color = team.Length > 0 ? theme.text : theme.textDisabled;
        }

        if (driverBio == null) return;

        if (row == null)
        {
            driverBio.text = "NO DRIVER RECORD";
            if (theme != null) driverBio.color = theme.textDisabled;
            return;
        }

        var parts = new List<string>(3);
        if (row.Age > 0) parts.Add("AGE " + row.Age);
        if (!string.IsNullOrWhiteSpace(row.Manufacturer)) parts.Add(row.Manufacturer.Trim().ToUpperInvariant());
        if (!string.IsNullOrWhiteSpace(row.Nickname)) parts.Add("\"" + row.Nickname.Trim().ToUpperInvariant() + "\"");

        driverBio.text = string.Join(" · ", parts);
        if (theme != null) driverBio.color = theme.textDim;
    }

    // Every attribute the Drivers table rates this driver on, in DriverAttributeSheet order — the same
    // order the builder laid the rows out in. A save with no row at all reads as unrated rather than
    // drawing eighteen empty bars.
    void FillDriverStats(PixelUITheme theme, Driver row)
    {
        var sheet = DriverAttributeSheet.All;
        for (int i = 0; i < driverStats.Count && i < sheet.Length; i++)
        {
            var attribute = sheet[i];
            int value = row != null ? attribute.Read(row) : -1;
            SetStat(driverStats, i, attribute.Label,
                    value >= 0 ? value / (float)Mathf.Max(1, attribute.Max) : 0f,
                    value >= 0 ? value.ToString() : "—");
            if (theme != null && driverStats[i].value != null)
                driverStats[i].value.color = value >= 0 ? theme.text : theme.textDisabled;
        }
    }

    // What the car will actually race with: the base VehicleInfo plus every installed part.
    void FillCarStats()
    {
        var baseInfo = Resources.Load<VehicleInfo>("Vehicles/Cup24");
        float topAdd = 0f, accelScale = 1f, gripAdd = 0f, wearScale = 1f;
        foreach (PartSlot slot in System.Enum.GetValues(typeof(PartSlot)))
        {
            var part = PlayerCarBuild.Installed(slot);
            if (part == null) continue;
            topAdd += part.topSpeedAdd;
            accelScale *= part.accelScale;
            gripAdd += part.gripAdd;
            wearScale *= part.wearScale;
        }

        float topSpeed = (baseInfo != null ? baseInfo.topSpeed : 200) + topAdd;
        float zeroSixty = (baseInfo != null ? baseInfo.zeroToSixty : 3.4f) / Mathf.Max(0.1f, accelScale);
        float grip = (baseInfo != null ? baseInfo.maxLateralG : 1.5f) + gripAdd;
        float durability = 1f / Mathf.Max(0.1f, wearScale);   // >1 = tyres last longer than stock

        SetStat(carStats, 0, "TOP SPEED", Mathf.InverseLerp(150f, 230f, topSpeed), Mathf.RoundToInt(topSpeed) + " MPH");
        SetStat(carStats, 1, "ACCEL", Mathf.InverseLerp(5f, 3f, zeroSixty), "0-60 " + zeroSixty.ToString("0.0") + "s");
        SetStat(carStats, 2, "GRIP", Mathf.InverseLerp(1f, 2f, grip), grip.ToString("0.00") + " G");
        SetStat(carStats, 3, "DURABILITY", Mathf.InverseLerp(0.7f, 1.4f, durability), DurabilityWord(durability));
    }

    static string DurabilityWord(float durability) =>
        durability >= 1.25f ? "IRON" : durability >= 1.05f ? "GOOD" :
        durability >= 0.95f ? "STOCK" : durability >= 0.8f ? "FAIR" : "FRAGILE";

    void FillParts(PixelUITheme theme)
    {
        var slots = new[] { PartSlot.Engine, PartSlot.Gearbox, PartSlot.Tires, PartSlot.Chassis };
        for (int i = 0; i < partRows.Count && i < slots.Length; i++)
        {
            var part = PlayerCarBuild.Installed(slots[i]);
            SetPair(partRows, i, slots[i].ToString().ToUpperInvariant(), part != null ? part.name : "stock");
            if (theme != null && partRows[i].value != null)
                partRows[i].value.color = part != null ? theme.text : theme.textDisabled;
        }
    }

    // ------------------------------------------------------------------ helpers

    void SetStat(List<StatRow> rows, int index, string label, float fill01, string value)
    {
        if (index < 0 || index >= rows.Count) return;
        var row = rows[index];
        if (row.label != null) row.label.text = label;
        if (row.value != null) row.value.text = value;
        if (row.cells != null)
            IronOvalUI.SetCells(row.cells, Mathf.RoundToInt(Mathf.Clamp01(fill01) * 10f), 10, row.tint);
    }

    static void SetPair(List<TextPair> rows, int index, string label, string value)
    {
        if (index < 0 || index >= rows.Count) return;
        if (rows[index].label != null) rows[index].label.text = label;
        if (rows[index].value != null) rows[index].value.text = value;
    }

    static void SetBar(RectTransform fill, float amount01)
    {
        if (fill == null || fill.parent is not RectTransform track) return;
        fill.sizeDelta = new Vector2(Mathf.Round(track.rect.width * Mathf.Clamp01(amount01)), fill.sizeDelta.y);
    }

    // ------------------------------------------------------------------ buttons (wired by the builder)

    public void Race()
    {
        if (!Application.CanStreamedLevelBeLoaded(raceSceneName))
        {
            SetStatus(raceSceneName + " isn't in the build settings yet.");
            return;
        }
        SceneManager.LoadScene(raceSceneName);
    }

    public void Back()
    {
        if (!Application.CanStreamedLevelBeLoaded(titleSceneName))
        {
            SetStatus(titleSceneName + " isn't in the build settings yet.");
            return;
        }
        SceneManager.LoadScene(titleSceneName);
    }

    void SetStatus(string text)
    {
        if (statusLabel == null) return;
        statusLabel.text = text ?? "";
        _statusUntil = string.IsNullOrEmpty(text) ? 0f : Time.unscaledTime + 2.5f;
    }
}
