using UnityEngine;

// Scene-placed RV/motorhome exterior (Assets/Prefabs/Environment/RV.prefab, generated by
// Draftmaster > RV Interior > Build RV Prefab). The prefab carries the SpawnPoint_RV marker as a
// child, so dropping one instance in a scene places the on-foot RV start, and moving/rotating the
// RV takes the spawn (and the masked interior anchored to it) along. The marker can be dragged
// freely within the RV to fine-tune where the player stands.
//
// The door's position and facing are serialized below (defaults match the current prefab: a
// side door on the local +X edge, toward the cab). RVInterior reads DoorWorldDirection so the
// interior room always lines up with how the RV is rotated in the scene (without an RVExterior
// ancestor, the door falls back to facing the parked car). Placeholder art is tinted rectangles
// under Body — swap in a real sprite there.
// The prefab also carries solid BoxCollider2D children outlining the body with a notch at the door,
// so the walking player can't pass through the shell from outside. RVInterior disables them while the
// player is inside (they overlap the room's floor) and re-enables them on stepping out.
public class RVExterior : MonoBehaviour
{
    [Tooltip("Direction the door faces in the RV's local frame (must match the collider notch). The gizmo arrow shows it.")]
    public Vector2 doorLocalDirection = Vector2.right;
    [Tooltip("Centre of the doorway in the RV's local frame (middle of the collider notch, on the body edge).")]
    public Vector2 doorLocalPosition = new Vector2(1.73f, 1.21f);

    // World-space doorway, however the RV instance is rotated in the scene.
    public Vector2 DoorWorldDirection => ((Vector2)transform.TransformDirection(doorLocalDirection)).normalized;
    public Vector3 DoorWorldPosition => transform.TransformPoint(new Vector3(doorLocalPosition.x, doorLocalPosition.y, 0f));

    // The player's parked motorhome, and only ever that.
    //
    // The masked interior room carries an RVExterior of its own at its root (the prefab
    // RVInteriorPrefabBuilder generates), and that room is in the scene from the moment the player spawns
    // inside it — so a plain FindObjectOfType can hand back a doorway in a pocket dimension instead of the
    // rig parked in the paddock. Everything that places itself against "the RV" goes through here.
    public static RVExterior Player
    {
        get
        {
            var all = FindObjectsByType<RVExterior>(FindObjectsInactive.Include, FindObjectsSortMode.None);

            RVExterior room = null;
            for (int i = 0; i < all.Length; i++)
            {
                if (all[i] == null) continue;
                if (all[i].GetComponentInParent<RVInterior>() != null) { room ??= all[i]; continue; }
                return all[i];
            }

            // Nothing but the room: better than nothing for anything that only needs a doorway to face.
            return room;
        }
    }

    // Raised when the rig is moved after the scene has opened, with the shift it made.
    //
    // Everything around a motorhome is placed against its doorway once, when the scene opens: the NPC
    // waiting outside, the walk-over trigger that starts their beat, the masked interior room, the career
    // -path NPC stood off the far corner. The driver motorhome lot then parks the rig into its place in the
    // field several seconds later, once the field has finished spawning — and without this they all stay
    // behind in an empty stretch of paddock, with a trigger the player never walks through again.
    //
    // A shift rather than a re-derive, so whatever each of them solved for spacing or walkability survives.
    public static event System.Action<Vector3> Moved;

    // Park the rig somewhere else in the ground plane. Rotation and z are kept: the doorway still faces the
    // way it was placed, so nothing listening has to do more than translate.
    public void MoveTo(Vector3 worldPoint)
    {
        Vector3 at = transform.position;
        var delta = new Vector3(worldPoint.x - at.x, worldPoint.y - at.y, 0f);
        if (delta.sqrMagnitude < 0.0001f) return;

        transform.position = at + delta;
        Moved?.Invoke(delta);
    }

    Collider2D[] _colliders;

    public void SetCollidersEnabled(bool value)
    {
        if (_colliders == null) _colliders = GetComponentsInChildren<Collider2D>(true);
        foreach (var c in _colliders)
            if (c != null) c.enabled = value;
    }

#if UNITY_EDITOR
    void OnDrawGizmos()
    {
        // Door-direction arrow (from the doorway itself) so the facing is obvious while placing.
        Gizmos.color = new Color(1f, 0.85f, 0.3f, 0.9f);
        Vector3 dir = DoorWorldDirection;
        Vector3 side = new Vector3(-dir.y, dir.x, 0f);
        Vector3 p = DoorWorldPosition;
        Vector3 tip = p + dir * 3f;
        Gizmos.DrawLine(p, tip);
        Gizmos.DrawLine(tip, tip - dir * 0.8f + side * 0.5f);
        Gizmos.DrawLine(tip, tip - dir * 0.8f - side * 0.5f);
        UnityEditor.Handles.color = Gizmos.color;
        UnityEditor.Handles.Label(tip + side * 0.3f, "RV door");
    }
#endif
}
