using UnityEngine;

// Scene-placed RV/motorhome exterior (Assets/Prefabs/Environment/RV.prefab, generated by
// Draftmaster > RV Interior > Build RV Prefab). The prefab carries the SpawnPoint_RV marker as a
// child, so dropping one instance in a scene places the on-foot RV start, and moving/rotating the
// RV takes the spawn (and the masked interior anchored to it) along. The marker can be dragged
// freely within the RV to fine-tune where the player stands.
//
// The door's position and facing are serialized below (defaults match the current prefab: a
// side door on the local +X edge, toward the cab). RVInterior reads DoorWorldDirection so the
// interior room always lines up with how the RV is rotated in the scene (without an RVExterior
// ancestor, the door falls back to facing the parked car). Placeholder art is tinted rectangles
// under Body — swap in a real sprite there.
// The prefab also carries solid BoxCollider2D children outlining the body with a notch at the door,
// so the walking player can't pass through the shell from outside. RVInterior disables them while the
// player is inside (they overlap the room's floor) and re-enables them on stepping out.
public class RVExterior : MonoBehaviour
{
    [Tooltip("Direction the door faces in the RV's local frame (must match the collider notch). The gizmo arrow shows it.")]
    public Vector2 doorLocalDirection = Vector2.right;
    [Tooltip("Centre of the doorway in the RV's local frame (middle of the collider notch, on the body edge).")]
    public Vector2 doorLocalPosition = new Vector2(1.875f, 0.383f);

    // World-space doorway, however the RV instance is rotated in the scene.
    public Vector2 DoorWorldDirection => ((Vector2)transform.TransformDirection(doorLocalDirection)).normalized;
    public Vector3 DoorWorldPosition => transform.TransformPoint(new Vector3(doorLocalPosition.x, doorLocalPosition.y, 0f));

    // The player's parked motorhome, and only ever that.
    //
    // The masked interior room carries an RVExterior of its own at its root (the prefab
    // RVInteriorPrefabBuilder generates), and that room is in the scene from the moment the player spawns
    // inside it — so a plain FindObjectOfType can hand back a doorway in a pocket dimension instead of the
    // rig parked in the paddock. Everything that places itself against "the RV" goes through here.
    public static RVExterior Player
    {
        get
        {
            var all = FindObjectsByType<RVExterior>(FindObjectsInactive.Include, FindObjectsSortMode.None);

            RVExterior room = null;
            for (int i = 0; i < all.Length; i++)
            {
                if (all[i] == null) continue;
                if (all[i].GetComponentInParent<RVInterior>() != null) { room ??= all[i]; continue; }
                return all[i];
            }

            // Nothing but the room: better than nothing for anything that only needs a doorway to face.
            return room;
        }
    }

    // Raised when the rig is moved after the scene has opened, with the shift it made.
    //
    // Everything around a motorhome is placed against its doorway once, when the scene opens: the NPC
    // waiting outside, the walk-over trigger that starts their beat, the masked interior room, the career
    // -path NPC stood off the far corner. The driver motorhome lot then parks the rig into its place in the
    // field several seconds later, once the field has finished spawning — and without this they all stay
    // behind in an empty stretch of paddock, with a trigger the player never walks through again.
    //
    // A shift rather than a re-derive, so whatever each of them solved for spacing or walkability survives.
    public static event System.Action<Vector3> Moved;

    // Park the rig somewhere else in the ground plane. Rotation and z are kept: the doorway still faces the
    // way it was placed, so nothing listening has to do more than translate.
    public void MoveTo(Vector3 worldPoint)
    {
        Vector3 at = transform.position;
        var delta = new Vector3(worldPoint.x - at.x, worldPoint.y - at.y, 0f);
        if (delta.sqrMagnitude < 0.0001f) return;

        transform.position = at + delta;
        if (_pocket != null) _pocket.position += delta;

        // Colliders only move with their transforms on the next simulation step. The player is shifted with
        // the room this same frame, and the very next FixedUpdate asks the boundaries whether they are
        // stood somewhere walkable — against the old pocket, that answer is no and they are clamped back.
        Physics2D.SyncTransforms();
        Moved?.Invoke(delta);
    }

    [Tooltip("Walkable ground kept round the rig past its bodywork (metres), so the player can step out of the " +
             "door wherever the rig is parked. Only built when the scene has a PaddockBoundary.")]
    public float walkablePad = 4f;

    Transform _pocket;

    // Wherever the rig is parked, the player can stand in it and step out of its door.
    //
    // The player wakes up inside this motorhome, and an authored PaddockBoundary clamps them to it from the
    // first frame. Park the rig out past that polygon — in the motorhome lot, where it belongs — and the
    // spawn was clamped to the nearest edge of the old paddock, the masked room built there, and walking
    // out of the door dropped them back where the RV used to be. The lot's own pocket fixes that, but only
    // seconds later, once the field is up. So the rig carries a pocket of its own from the start: a
    // separate object (not a child, or SetCollidersEnabled would switch it off while the player is inside)
    // that MoveTo carries along. Only when a boundary is already active, or it would newly fence the player
    // into one motorhome on a scene that has no boundary at all.
    public void InstallWalkablePocket()
    {
        if (_pocket != null || !PaddockBoundary.AnyActive) return;

        bool any = false;
        var box = new Bounds(transform.position, Vector3.zero);
        foreach (var c in GetComponentsInChildren<Collider2D>(true))
        {
            if (c == null || c.isTrigger) continue;
            if (!any) { box = c.bounds; any = true; }
            else box.Encapsulate(c.bounds);
        }
        if (!any) box = new Bounds(transform.position, new Vector3(10f, 10f, 0f));
        box.Expand(new Vector3(walkablePad * 2f, walkablePad * 2f, 0f));

        var go = new GameObject(name + "WalkablePocket");
        go.transform.SetPositionAndRotation(Vector3.zero, Quaternion.identity);   // local space == world space
        var poly = go.AddComponent<PolygonCollider2D>();
        poly.points = new[]
        {
            new Vector2(box.min.x, box.min.y),
            new Vector2(box.max.x, box.min.y),
            new Vector2(box.max.x, box.max.y),
            new Vector2(box.min.x, box.max.y),
        };
        go.AddComponent<PaddockBoundary>();
        Physics2D.SyncTransforms();
        _pocket = go.transform;
    }

    void OnDestroy()
    {
        if (_pocket == null) return;
        if (Application.isPlaying) Destroy(_pocket.gameObject);
        else DestroyImmediate(_pocket.gameObject);
    }

    Collider2D[] _colliders;

    public void SetCollidersEnabled(bool value)
    {
        if (_colliders == null) _colliders = GetComponentsInChildren<Collider2D>(true);
        foreach (var c in _colliders)
            if (c != null) c.enabled = value;
    }

#if UNITY_EDITOR
    void OnDrawGizmos()
    {
        // Door-direction arrow (from the doorway itself) so the facing is obvious while placing.
        Gizmos.color = new Color(1f, 0.85f, 0.3f, 0.9f);
        Vector3 dir = DoorWorldDirection;
        Vector3 side = new Vector3(-dir.y, dir.x, 0f);
        Vector3 p = DoorWorldPosition;
        Vector3 tip = p + dir * 3f;
        Gizmos.DrawLine(p, tip);
        Gizmos.DrawLine(tip, tip - dir * 0.8f + side * 0.5f);
        Gizmos.DrawLine(tip, tip - dir * 0.8f - side * 0.5f);
        UnityEditor.Handles.color = Gizmos.color;
        UnityEditor.Handles.Label(tip + side * 0.3f, "RV door");
    }
#endif
}
